### PR TITLE
Speed optimisations

### PR DESCRIPTION
**Pull request by maxim-zhao**
- Join table and handlers so you can use inc h
- Move type E handler inline to avoid a jump

### CODE REVIEW

**Comment by sverx** [comment]
Thanks! :+1:

**Comment by sverx** [comment]
I now also added the missing DI/EI when setting the VDP address, that was missing since then...

**Comment by maxim-zhao** [comment]
I can think of a few scenarios regarding interrupts:

1. Interrupts are already disabled, your `ei` will turn them on again...
2. Screen is off, no interrupts will happen anyway (most common case?)
3. Screen is on and interrupts are enabled, an interrupt may happen at any time and is likely to disrupt the VDP state such that later writes to VRAM end up in the wrong place (most likely during screen-on IMO)
4. Screen is on and interrupts are enabled, but interrupts just read the control port. I think in this case the address setting may be at risk, and protected by your `di`/`ei`, but I think it's a minority case.

**Comment by sverx** [comment]
true, and this code presumes that interrupts are enabled when calling this routine but also try to avoid issues with the VDP by keeping the two writes for the address undisturbed

depending on the use case, as you know, those `EI`/`DI` should be removed or a different approach on the whole operation should be taken, but this is beyond the scope of this repository IMHO

**Pull request merged**
